### ISSUE TITLE
Issue concerning the number of letters of "name" from expt_name and input_name folders ?

### ISSUE THREAD

**Issue by Anthowi** [beatrixparis/connectivity-modeling-system#29]
Dear all,

I am new to cms. I am using it with my own oceanographic data. 
I installed it and it works but I noticed depending on the number of letters of my experiment name I get a "rename Error: No such file or directory" when I run cms and my output traj_file_1.nc goes into the SCRATCH folder (the trajectories in the output file seem correct though).
Actually, I get this if the number of letters is 5, but if this number is more or less, everything is okay.
Here are the names of my folders: expt_NIDOR
                                                       input_NIDOR

Does anyone knows if I missed something somewhere ?

Thanks a lot for your help

**Comment by salwood82** [comment]
Hi,
I regularly run experiments with names over 5 characters in length, so that's not your problem. Also, if you are getting a traj_file in your SCRATCH directory CMS must be finding your input_ and expt_ dirs. I suggest you do some more investigating and post to the CMS users forum (email connectivity-modeling-system-club@googlegroups.com) with more information on your inputs and what error/output messages you are getting. 
Sally

**Comment by Anthowi** [comment]
Thanks Sally

**Comment by silvaglx** [comment]
I'm sorry to reopen this issue after a long time, but I can confirm that CMS do seems to have a bug when using *5 digits* experiment names. Your files will not be moved from /SCRATCH to /output at the end of the simulation, receiving the "rename Error: No such file or directory". However, as mentioned by @Anthowi if you use more or less than 5 digits it works.
