### ISSUE TITLE
can't open module file netcdf.mod

### ISSUE THREAD

**Issue by anthonysnead** [beatrixparis/connectivity-modeling-system#34]
I m trying to install cms on my ubuntu terminal. I am really new to this work, but I really want to use the software. I have installed mpif90, gfortran, and gcc. I installed netcdf as well but not I get a fatal error that I cannot open netcdf.mod. Thank you for your help this is what it looks like. 

mpif90 -c mod_netcdf.f90 -I/usr/local/netcdf/include -I/usr/local/include
f951: Warning: Nonexistent include directory ‘/usr/local/netcdf/include’ [-Wmissing-include-dirs]
mod_netcdf.f90:28:4:

 USE netcdf
    1
Fatal Error: Can't open module file ‘netcdf.mod’ for reading at (1): No such file or directory
compilation terminated.
../arch/mpi_compiler:24: recipe for target 'mod_netcdf.o' failed
make: *** [mod_netcdf.o] Error 1

**Comment by bexeross** [comment]
Hi Anthony, 
Please join our google group where we can help more with installation issues and many have been discussed and solutions suggested. 

https://groups.google.com/forum/#!forum/connectivity-modeling-system-club

I think your problem is that after version 4.2 of Netcdf they split the C and fortran libraries into different installations - now you have to install the netcdf-fortran libraries separately. Try that and see if it helps. If not, please check the google group for other suggestions and then post there with your specific issue if the forum suggestions cannot help.

All the best,
Bex
