### ISSUE TITLE
Problem with getdata - failure to change the fill value of u and v velocity (managed to change vertical velocity)

### ISSUE THREAD

**Issue by Doria-Zhang** [beatrixparis/connectivity-modeling-system#44]
Dear all,

    I use HYCOM GLbu data (I first archived them in expt_name/nests/raw directory) to conduct CMS experiments, and first I use ./getdata to create new nc files, but still **my zu and zv has a fillvalue of -30**, while zw has a fillvalue equal to the CMS value (1.2676506E30). Therefore, my trajectorys seem wierd. Particles  **propelled through land at often very high speed.** 
    I don't know why   ./getdata didn't change the fillvalue of horizontal velocities, and I hope you can help me find where is potentially the problem.

Thanks a lot!

**Comment by beatrixparis** [comment]
Hello Doria-Zhang,

This is the new standard for the HYCOM files. The user needs to specify the field "fill_value" in the nest_1.nml to download the data, in this case, -30. Getdata will then use our standard missing value (1.2676506E30) when writing the nest files.

If one field has a fill value and another field has a different value, they will need to correct it with a post-processing script, as getdata considers that all fields will have the same fill value (which is usually the case). But I am pretty sure the Global Hycom does not have w, which is why it must be filled with the correct missing value (1.2676506E30), for all points.

Best

Ana Vaz and Claire Paris



Claire B. Paris-Limouzy, PhD (she/her)
____________________________________

Professor, Department of Ocean Sciences
Rosenstiel School of Marine, Atmospheric, and Earth Science
University of Miami
4600 Rickenbacker Causeway, Miami, FL 33149-1098, USA
Phone: 305-421-4219, Fax: 305-421-4701
Marine Technology & Life Science Seawater (MTLSS) #245

UM ***@***.***
ORCID https://orcid.org/0000-0002-0637-1334
UM Research Profile:https://miami.pure.elsevier.com/en/persons/claire-b-paris-limouzy
open-source Connectivity Modeling System https://github.com/beatrixparis

“If you lose small things everything else fails” Louie Psihoyos

________________________________
From: Doria-Zhang ***@***.***>
Sent: Wednesday, August 23, 2023 9:21 AM
To: beatrixparis/connectivity-modeling-system ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [beatrixparis/connectivity-modeling-system] Problem with getdata - failure to change the fill value of u and v velocity (managed to change vertical velocity) (Issue #44)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

Dear all,

I use HYCOM GLbu data (I first archived them in expt_name/nests/raw directory) to conduct CMS experiments, and first I use ./getdata to create new nc files, but still **my zu and zv has a fillvalue of -30**, while zw has a fillvalue equal to the CMS value (1.2676506E30). Therefore, my trajectorys seem wierd. Particles  **propelled through land at often very high speed.**
I don't know why   ./getdata didn't change the fillvalue of horizontal velocities, and I hope you can help me find where is potentially the problem.


Thanks a lot!

**Comment by Doria-Zhang** [comment]
Dear Ana and Claire,

    Thanks for your answer. In fact I made a mistake, the fill value of zu and zv is right, but ./getdata did not recognize the 
original fill value of u and v, that is, -30, and replace them. So the valid range was between -30 and the upper limit.  I don't 
know if any post-processing should be done, or may I need to change the getdata.f90 original code? By the way, the original
type of u and v were short, I don't know whether it influence the convertion of fill value.

    As below is an example of my ./getdata output. 


        float zu(Time, Depth, Latitude, Longitude) ;
                zu:long_name = "eastward_sea_water_velocity" ;
                zu:units = "m/s" ;
                zu:_FillValue = 1.267651e+30f ;
                zu:valid_range = -30.f, 2.094f ;
        float zv(Time, Depth, Latitude, Longitude) ;
                zv:long_name = "northward_sea_water_velocity" ;
                zv:units = "m/s" ;
                zv:_FillValue = 1.267651e+30f ;
                zv:valid_range = -30.f, 1.516f ;
        float zw(Time, Depth, Latitude, Longitude) ;
                zw:long_name = "downward_sea_water_velocity" ;
                zw:units = "m/s" ;
                zw:_FillValue = 1.267651e+30f ;
                zw:valid_range = -9.96921e+36f, 0.006610697f ;


Thanks!

**Comment by Doria-Zhang** [comment]
Dear Professor,

     Recently I would like to use another Dataset, not HYCOM, to drive cms
tracking. And I put u,v,w in different files.
     In the section 4.3.2 and 4.4 of CMS user guide v2 (page 26-27), I see
that there is an example of  nest_1_20101004010000u.nc,
as the picture show, but I do not know how to write the nest_1.xml file to
recognise the different files by using getdata combining
nest_1.xml. Specificly, in the raw file,  from different data, xaxis,
yaxis, zaxis, taxis are different (The raw data is B-grid), I am not sure
whether I need to write as xaxisU, xaxisV, xaxisW, yaxisU, yaxisV, yaxisW,
zaxisU, zaxisV, zaxisW.
     Another question is, if my raw fields are saved in different files,
could the output of the formatted file be stored at the same file?
[image: image.png]
4.3.2 Formatting locally stored files with getdata
4.4 Using your own nest files

[image: image.png]

     Thank you for your time!

Sincerely,
Doria


Claire B. Paris ***@***.***> 于2023年8月24日周四 01:17写道：
